core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = "mover.views.custom_404"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mover.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('payments/', include('payments.urls')),
]

if settings.DEBUG:
    # Add URLs for debugging purposes
    # urlpatterns += [
    #     path("__reload__/", include("django_browser_reload.urls")),

    # ]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mover/urls.py
from django.urls import path
from .views import (document_verification, login, logout_view, fulfill_request, payment_success,
                    request_mover, accept_request, select_mover, signup, application_status, payment_detail,
                    ready_to_move, vehicle_information, list_fulfilled_requests, payment_failure,
                    ready_to_move_customer, before_moving, send_email, home, home_driver)

urlpatterns = [
    path('', home, name="home"),
    path('payment/success/', payment_success, name="payment_success"),
    path('payment/failure/', payment_failure, name="payment_failure"),
    path('payment/detail/<int:payment_id>', payment_detail, name="payment_detail"),
    path('driver/', home_driver, name="home_driver"),
    path('request-mover', request_mover, name="request_mover"),
    path('select-mover/<str:tracking_id>/', select_mover, name="select_mover"),
    path('accept-request/', accept_request, name="accept_request"),
    path('before-moving/<str:tracking_id>/',
         before_moving, name="before_moving"),
    path('ready-to-move/',
         ready_to_move, name="ready_to_move"),
    path('ready-to-move/customer/<int:pk>/<str:tracking_id>/', ready_to_move_customer,
         name="ready_to_move_customer"),
    path("fulfilled-requests/", list_fulfilled_requests,
         name="list_fulfilled_requests"),
    path("fulfill-request/<int:id>/", fulfill_request, name="fulfill_request"),
    path("signup/", signup, name="signup"),
    path("login/", login, name="login"),
    path("logout_view/", logout_view, name="logout_view"),
    path("document/verification", document_verification,
         name="document_verification"),
    path("vehicle/information", vehicle_information, name="vehicle_information"),
    path("application/status", application_status, name="application_status"),
    path('send-email/', send_email, name="send_email"),
]

mover/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext as _

from django.contrib.auth.base_user import BaseUserManager
from .utils import get_driving_data2, get_lat_long
# Create your models here.
from decimal import Decimal

from payments import PurchasedItem
from payments.models import BasePayment


class Payment(BasePayment):

    def get_failure_url(self) -> str:
        # Return a URL where users are redirected after
        # they fail to complete a payment:
        return f"http://localhost:8000/payment/failure/"

    def get_success_url(self) -> str:
        # Return a URL where users are redirected after
        # they successfully complete a payment:
        return f"http://localhost:8000/payment/success/"

    def get_purchased_items(self):
        # Return items that will be included in this payment.
        yield PurchasedItem(
            name='The Hound of the Baskervilles',
            sku='BSKV',
            quantity=9,
            price=Decimal(10),
            currency='USD',
        )


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifier
    for authentication instead of usernames.
    """

    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_('Users must have an email address'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    charging_rate = (
        ("FX", "Fixed"),
        ("HR", "Hourly"),
    )
    ROLE_CHOICES = (
        ('driver', 'Driver'),
        ('customer', 'Customer'),
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    username = None

    email = models.EmailField(_('email address'), unique=True)
    role = models.CharField(
        max_length=10, choices=ROLE_CHOICES, null=True, blank=True, default="driver")
    address = models.CharField(max_length=300, null=True, blank=True)
    address_latitude = models.FloatField(null=True)
    address_longitude = models.FloatField(null=True)
    profile_picture = models.ImageField(
        upload_to="images/", null=True, blank=True)
    phone_number = models.CharField(
        max_length=200)  # Not nullable and not blank
    is_verified = models.BooleanField(default=False, null=True, blank=True)
    rate_of_service = models.CharField(
        max_length=100, choices=charging_rate, null=True, blank=True)
    hourly_amount = models.IntegerField(null=True, blank=True)
    fixed_amount = models.IntegerField(null=True, blank=True)
    minutes_away = models.IntegerField(null=True, blank=True)
    rating = models.IntegerField(null=True, blank=True)
    drivers_license_number = models.IntegerField(null=True, blank=True)
    license_expiration = models.DateField(null=True, blank=True)
    license_state = models.CharField(max_length=200, null=True, blank=True)
    license_zipcode = models.CharField(max_length=200, null=True, blank=True)
    # drivers_license = models.FileField(null=True, blank=True)
    drivers_license_front = models.ImageField(upload_to="images/", null=True)
    drivers_license_back = models.ImageField(upload_to="images/", null=True)

    def __str__(self):
        return self.first_name

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_cordinates(self):
        if self.address_latitude == None or self.address_longitude == None:
            return None

        return f"{self.address_latitude},{self.address_longitude}"

    def set_cordinates(self):
        if not self.address:
            raise ValueError(f"{self.get_full_name()} Address field is empty")
        (lat, long) = get_lat_long(self.address)

        self.address_latitude = lat
        self.address_longitude = long

    def set_minutes_away(self, pickup_cordinate: str, save: bool = False) -> int:
        """
            This sets the driver's minutes away.
            Arguments: 
                pickup_cordinate: str
                save: bool
            Example:
                get_minutes_away("-232.3223, 232.2323", save=True)
        """
        driver_cordinates = self.get_cordinates()

        if not driver_cordinates:
            return None

        (distance, duration) = get_driving_data2(
            pickup_cordinate, driver_cordinates)

        if save:
            self.minutes_away = duration
            self.save()

        return (distance, duration)


class Vehicle(models.Model):

    VEHICLE_TYPE = (
        ('SUV', 'SUV'),
        ('MiniVan', 'MiniVan'),
        ('Cargo Van', 'Cargo Van'),
        ('Pick Up Truck', 'Pick Up Truck'),
    )

    license_plate = models.CharField(max_length=200)
    year = models.CharField(max_length=200)
    make = models.CharField(max_length=200)
    model = models.CharField(max_length=200)
    is_available = models.BooleanField(default=True)
    is_loading = models.BooleanField(default=True)
    is_unloading = models.BooleanField(default=True)
    vehicle_insurance = models.FileField(upload_to="documents/")
    # vehicle_photo = models.ImageField(upload_to="images/")
    interior_vehicle_photo = models.ImageField(upload_to="images/", null=True)
    exterior_front_vehicle_photo = models.ImageField(upload_to="images/", null=True)
    exterior_back_vehicle_photo = models.ImageField(upload_to="images/", null=True)
    exterior_side_vehicle_photo = models.ImageField(upload_to="images/", null=True)
    driver = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    vehicle_type = models.CharField(
        max_length=200, null=True, choices=VEHICLE_TYPE)

    def __str__(self):
        return f"{self.make} - {self.model}"

    def get_vehicle_full_name(self):
        return f"{self.year} {self.make} {self.model}"


class VehiclePhoto(models.Model):
    photo = models.ImageField(upload_to="images")
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)


class Booking(models.Model):

    MEDIUM_VEHICLE_BASE_FEE = 38
    MEDIUM_VEHICLE_BASE_FEE_PER_MILE = 2.25

    SMALL_VEHICLE_BASE_FEE = 26
    SMALL_VEHICLE_BASE_FEE_PER_MILE = 1.95

    ITEM_CHOICES = (
        ('1-2', '1 - 2 items'),
        ('3-5', '3 - 5 items'),
        ('6-10', '6 - 10 items'),
        ('11-15', '11 - 15 items'),
    )
    RATE_TYPE = (
        ("FX", "Fixed"),
        ("HR", "Hourly"),
    )
    SERVICE_TYPE = (
        ("LOAD", "Load"),
        ("UNLOAD", "Unload"),
        ("BOTH", "Both"),
    )
    VEHICLE_TYPE_CHOICES = (
        ('SUV', 'SUV'),
        ('MiniVan', 'MiniVan'),
        ('Cargo Van', 'Cargo Van'),
        ('Pickup Truck', 'Pickup Truck'),
    )
    HANDLE_LOADING = (
        ("1", "Carry up/down stairs"),
        ("2", "Curbside pick-up/drop-off"),
        ("3", "Elevator"),
        ("4", "None of the Above"),
    )
    owner = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name="driver_bookings", null=True, blank=True)
    vehicle = models.ForeignKey(
        Vehicle, on_delete=models.CASCADE, null=True, blank=True)
    pickup_location = models.CharField(max_length=300)
    dropoff_location = models.CharField(max_length=300)
    pickup_longitude = models.CharField(max_length=300, null=True)
    pickup_latitude = models.CharField(max_length=300, null=True)
    dropoff_longitude = models.CharField(max_length=300, null=True)
    dropoff_latitude = models.CharField(max_length=300, null=True)
    total_distance = models.IntegerField(null=True, blank=True)  # in miles
    estimated_duration = models.IntegerField(
        null=True, blank=True)  # in minutes
    # arrival_time = models.IntegerField(
    #     null=True, blank=True)  # driver arrival time
    total_amount = models.IntegerField(null=True, blank=True)
    email = models.CharField(max_length=300, null=True)
    tracking_id = models.CharField(
        max_length=200, null=True, blank=True, unique=True)
    is_fulfilled = models.BooleanField(default=False, null=True)
    is_accepted = models.BooleanField(default=False, null=True)
    selected_item = models.CharField(
        max_length=5,
        choices=ITEM_CHOICES,
        default='1-2',
        null=True,
    )
    vehicle_type = models.CharField(
        max_length=50,
        choices=VEHICLE_TYPE_CHOICES,
        default="Pickup Truck"
    )
    service_type = models.CharField(
        max_length=100, choices=SERVICE_TYPE, null=True, default="LOAD")
    rate_type = models.CharField(
        max_length=100, choices=RATE_TYPE, null=True, default="FX")
    handle_loading = models.CharField(
        max_length=100, choices=HANDLE_LOADING, null=True, default="4")
    photo = models.ImageField(upload_to="images/", null=True)
    note = models.CharField(max_length=400, null=True)

    def __str__(self) -> str:
        return f"Booking - {self.tracking_id}"

    def set_tracking_id(self):
        self.tracking_id = str(uuid.uuid4())

    def get_cordinates(self):
        pickup = f"{self.pickup_latitude},{self.pickup_longitude}"
        dropoff = f"{self.dropoff_latitude},{self.dropoff_longitude}"
        return (pickup, dropoff)

    def set_cordinates(self):
        if self.pickup_location is None or self.dropoff_location is None:
            raise ValueError(

mover/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django import forms
from .models import CustomUser, Vehicle, Booking
from django.core.validators import MaxValueValidator


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email', 'address', 'password1',
                  'password2', 'profile_picture', 'phone_number')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', "last_name")


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'password')


class DocumentVerificationForm(UserChangeForm):

    license_expiration = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'})
    )

    class Meta:
        model = CustomUser
        fields = ('drivers_license_number', 'license_expiration', 'license_state',
                  'license_zipcode', 'drivers_license_front', "drivers_license_back")


# class VehicleInformationForm(forms.ModelForm):

#     class Meta:
#         model = Vehicle
#         fields = ('license_plate', 'year', 'make', 'model',
#                   'vehicle_insurance', 'interior_vehicle_photo', 'exterior_front_vehicle_photo',
#                   'exterior_back_vehicle_photo', 'exterior_side_vehicle_photo')
#         widgets = {
#             'year': forms.NumberInput(attrs={'type': 'number'}),
#         }

class VehicleInformationForm(forms.ModelForm):
    # Add validators to the 'year' field
    year = forms.IntegerField(
        widget=forms.NumberInput(attrs={'type': 'number'}),
        validators=[MaxValueValidator(9999)]
    )

    class Meta:
        model = Vehicle
        fields = ('license_plate', 'year', 'make', 'model',
                  'vehicle_insurance', 'interior_vehicle_photo', 'exterior_front_vehicle_photo',
                  'exterior_back_vehicle_photo', 'exterior_side_vehicle_photo')


class BookingForm(forms.ModelForm):

    # selected_item = forms.DateField(
    #     widget=forms.DateInput(attrs={'type': 'date'})
    # )
    class Meta:
        model = Booking
        fields = ("pickup_location", "dropoff_location", "email",
                  "service_type", "rate_type",
                  )
        widgets = {
            # 'selected_item': forms.RadioSelect,
            'service_type': forms.RadioSelect,
            'rate_type': forms.RadioSelect,
            'email': forms.EmailInput()
        }


class BookingUpdateForm(forms.ModelForm):

    class Meta:
        model = Booking
        fields = ("selected_item", "handle_loading", "photo", "note")
        widgets = {
            'selected_item': forms.RadioSelect,
            'handle_loading': forms.RadioSelect,
        }

templates/mover/driver_pages/accept_request.html
{% extends "mover/map_base.html" %}
{% load static %}

{% block title %}
<title>Accept Request</title>
<style>
    .mover-request-list p {
        line-height: 0.5em;
        font-size: 14px;
    }

    div.driver-accept-list:hover {
        background-color: #E0F0EE;
    }
</style>
{% endblock title %}

{% block cardRight %}


<div>
    <!-- If driver can accept request show all bookings wihtout a driver asigned -->
    {% if can_not_accept %}
    <h3>Accepted requests</h3>
    <p class="text-small">Please fufill these request before accepting more!</p>
    {% for booking in can_not_accept %}
    <div class="driver-accept-list p-2">
        <div class="d-flex flex-column flex-md-row gap-2 justify-content-between">
            <div class="d-flex flex-column flex-md-row gap-2">
                <div class="flex-grow-1">
                    <img src="{{ booking.photo.url }}" alt="" width=" 174px" height="106px" class="rounded img-fluid">
                </div>
                <div class="mover-request-list">
                    <p><b>{{ booking.selected_item }} Items </b></p>
                    <p style="color: #104333;" class="text-uppercase fw-bold">{{ booking.service_type }}</p>
                    <p>
                        <b style="color: #4A4A68;">Pick-up location:</b>
                        {{ booking.pickup_location }}
                    </p>
                    <p>
                        <b style="color: #4A4A68;">Pick-up location:</b>
                        {{ booking.dropoff_location }}
                    </p>
                    <p><b style="color: #4A4A68;">Est. driving distance:</b> 20 min</p>
                    <p>Note: {{ booking.note|truncatechars:28 }} </p>
                </div>
            </div>
            <div class="d-flex flex-row flex-md-column justify-content-evenly align-items-center">
                <p><span class="badge bg-danger" style="font-weight: 500;">Unfulfilled
                    </span></p>
                {% if booking.rate_type == "FX" %}
                <p class="mb-2">${{ user.fixed_amount }}/Fixed</p>
                {% else %}
                <p class="mb-2">${{ user.hourly_amount }}/Hourly</p>
                {% endif %}
                <form action="{% url 'fulfill_request' booking.id %}" method="POST">
                    {% csrf_token %}
                    {{ form.errors }}
                    <input type="hidden" name="tracking_id" value="{{ booking.tracking_id }}">
                    <button type="submit">Fulfilled?</button>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}

    {% else %}
    <h3>Available nearby requests</h3>
    <p class="text-small">Move items that work best for you!</p>
    {% for booking in all_orders %}
    {{ booking.is_accepted }}
    <div class="driver-accept-list p-2">
        <div class="d-flex flex-row gap-2 justify-content-between">
            <div class="d-flex flex-row gap-2">
                <div>
                    {% if booking.photo %}
                    <img src="{{ booking.photo.url }}" alt="" width=" 174px" class="rounded">
                    {% else %}
                    <img src="{% static 'images/no-image.png' %}" alt="" width=" 174px" class="rounded">
                    {% endif %}
                </div>
                <div class="mover-request-list">
                    <p><b>{{ booking.selected_item }} Items </b></p>
                    <p style="color: #104333;" class="text-uppercase fw-bold">{{ booking.service_type }}</p>
                    <p>
                        <b style="color: #4A4A68;">Pick-up location:</b>
                        {{ booking.pickup_location }}
                    </p>
                    <p><b style="color: #4A4A68;">Est. driving distance:</b>
                        {{ booking.total_distance }} miles, {{ booking.estimated_duration }} mins
                    </p>
                    <p>Note: {{ booking.note|truncatechars:20 }} </p>
                </div>
            </div>
            <div class="d-flex flex-column justify-content-center align-items-center">
                {% if booking.rate_type == "FX" %}
                <p class="mb-2">${{ user.fixed_amount }} / Fixed</p>
                {% else %}
                <p class="mb-2">${{ user.hourly_amount }} / Hourly</p>
                {% endif %}
                <form action="{% url 'ready_to_move' %}" method="POST">
                    {% csrf_token %}
                    {{ form.errors }}
                    <input type="hidden" name="tracking_id" value="{{ booking.tracking_id }}">
                    <button type="submit">Accept</button>
                </form>
            </div>
        </div>
    </div>
    {% empty %}
    <div>You don't have any booking requests yet.</div>
    {% endfor %}

    {% endif %}

</div>
{% endblock cardRight %}

templates/mover/driver_pages/application_status.html
{% extends "mover/index.html" %}
{% load static %}
{% block title %}
    <style>
        /* div.driver-onboarding-panel > div{
            margin-bottom: 1em;
        } */
    </style>
    <title>Application Status</title>
{% endblock title %}

{% block content %}
<div style="margin: 100px;" class="driver-onboarding-panel d-flex flex-lg-row flex-sm-column gap-4">
    <div class="driver-onboard-left">
        <div class="progress mb-4">
            <div class="progress-bar progress-bar-striped progress-bar-animated" 
            role="progressbar" style="width: 100%; background-color: #104333;"
            aria-valuenow="35" aria-valuemin="0" aria-valuemax="100">100% - Pending...</div>
        </div>
        <p>Step 1: Create account</p>
        <p><a href="{% url 'document_verification' %}" 
            class="text-decoration-none text-dark mover-onboarding-links">Step 2. Document Verification</a>
        </p>
        <p ><a href="{% url 'vehicle_information' %}" 
            class="text-decoration-none text-dark mover-onboarding-links">Step 3. Vehicle Information </a>
        </p>
        <p class="fw-bold"><a href="{% url 'application_status' %}" 
            class="text-decoration-none text-dark mover-onboarding-links">Step 4. Application Status </a>
        </p>
    </div>
    <div class="driver-onboard-right d-flex flex-column gap-4">
        <h3>Step 4. Application Status</h3>
        <div class="row">
            <div class="col">
                <p><b>Status:</b> Pending</p>
                <button><a href="{% url 'home' %}" 
                    class="text-white text-decoration-none text-uppercase">
                    Go to Dashboard
                </a></button>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/mover/driver_pages/ready_to_move.html
{% extends "mover/map_base.html" %}
{% load static %}

{% block title %}
<title>Ready To Move</title>
<style>
    div.driver-item-list p {
        line-height: 0.5em;
        font-size: 14px;
        color: #333333;
    }

    div.driver-detail-card {
        padding: 50px;
    }
</style>
{% endblock title %}

{% block cardRight %}
<div class="driver-detail-card">
    <h3 class="fw-900">Get ready to move!</h3>
    {% if booking.rate_type == "FX" %}
    <p class="fw-bold">
        You'll earn
        <span style="color: #12B76A;">
            ${{ user.fixed_amount }} fixed
        </span> moving {{ booking.selected_item }} items.
    </p>
    {% else %}
    <p class="fw-bold">
        You'll earn
        <span style="color: #12B76A;">
            ${{ user.hourly_amount }} / hour
        </span> moving {{ booking.selected_item }} items.
    </p>
    {% endif %}
    <div class="driver-item-list p-2" style="background-color: #E0F0EE;">
        <div><img src="{{ booking.photo.url }}" alt="" width="100%" height="236px" class="rounded"></div>
        <p class="mt-2"><b>Details</b></p>
        <p><b>Pick-up location: </b>{{ booking.pickup_location }}</p>
        <p><b>Destination: </b> {{ booking.dropoff_location }} </p>
        <p><b>Items: </b>{{ booking.selected_item }} items</p>
        <p><b>Service: </b>{{ booking.get_service_type_display }}, {{ booking.get_handle_loading_display }}</p>
        <p class="text-sm" style="font-size: 12px;"><b>Note: </b> {{ booking.note }} </p>
    </div>
    <div class="d-flex justify-content-center align-items-center">
        <button class="btn btn-outline fw-bold text-uppercase" style="color: #104333;">Cancel Trip</button>
    </div>
</div>
{% endblock cardRight %}

templates/mover/driver_pages/vehicle_information.html
{% extends "mover/index.html" %}
{% load static %}
{% block title %}
<title>Vehicle Information</title>
{% endblock title %}

{% block content %}

<div style="margin: 100px;" class="driver-onboarding-panel d-flex flex-lg-row flex-sm-column gap-4">
    <div class="driver-onboard-left">
        <div class="progress mb-4">
            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                style="width: 80%; background-color: #104333;" aria-valuenow="35" aria-valuemin="0" aria-valuemax="100">
                80%</div>
        </div>
        <p>Step 1: Create account</p>
        <p><a href="{% url 'document_verification' %}"
                class="text-decoration-none text-dark mover-onboarding-links">Step 2. Document Verification</a>
        </p>
        <p class="fw-bold"><a href="{% url 'vehicle_information' %}"
                class="text-decoration-none text-dark mover-onboarding-links">Step 3. Vehicle Information </a>
        </p>
        <p><a href="{% url 'application_status' %}" class="text-decoration-none text-dark mover-onboarding-links">Step
                4. Application Status </a>
        </p>
    </div>
    <form class="driver-onboard-right d-flex flex-column gap-4" method="POST" enctype="multipart/form-data"
        action="{% url 'vehicle_information' %}">
        {% csrf_token %}
        <h3>Step 3: Vehicle Information</h3>
        {{ form.errors }}
        <div class="row">
            <div class="col-lg-6 col-sm-12">
                <div class="d-flex flex-column">
                    <label for="">License Plate #</label>
                    <!-- <input type="text" name="firstname" id="" placeholder="License Plate #"> -->
                    {{ form.license_plate }}
                </div>
            </div>
            <div class="col-lg-6 col-sm-12">
                <div class="d-flex flex-column dropdown-container">
                    <!-- {{ form.year }} -->
                    <label for="id_year">Year</label>
                    <input type="number" name="year" id="id_year" required list="year_list" max="2023">
                    <datalist id="year_list">
                        <!-- Generate options for years from 2000 to 2023 -->
                        {% for year in year_list %}
                        <option value="{{ year }}">
                            {% endfor %}
                    </datalist>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-sm-12">
                <div class="d-flex flex-column">
                    <label for="">Make</label>
                    <!-- <input type="text" name="firstname" id="" placeholder="Email Address"> -->
                    {{ form.make }}
                </div>
            </div>
            <div class="col-lg-6 col-sm-12">
                <div class="d-flex flex-column">
                    <label for="">Model</label>
                    <!-- <input type="text" name="firstname" id="" placeholder="Phone Number"> -->
                    {{ form.model }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-sm-12">
                <div class="d-flex flex-column">
                    <label for="">Interior Vehicle Photo</label>
                    <!-- <input type="text" name="firstname" id="" placeholder="Email Address"> -->
                    {{ form.interior_vehicle_photo }}
                </div>
            </div>
            <div class="col-lg-6 col-sm-12">
                <div class="d-flex flex-column">
                    <label for="">Front Exterior Vehicle Photo</label>
                    <!-- <input type="text" name="firstname" id="" placeholder="Phone Number"> -->
                    {{ form.exterior_front_vehicle_photo }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-sm-12">
                <div class="d-flex flex-column">
                    <label for="">Back Exterior Vehicle Photo</label>
                    <!-- <input type="text" name="firstname" id="" placeholder="Phone Number"> -->
                    {{ form.exterior_back_vehicle_photo }}
                </div>
            </div>
            <div class="col-lg-6 col-sm-12">
                <div class="d-flex flex-column">
                    <label for="">Side Exterior Vehicle Photo</label>
                    <!-- <input type="text" name="firstname" id="" placeholder="Phone Number"> -->
                    {{ form.exterior_side_vehicle_photo }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="d-flex flex-column">
                    <label for="">Vehicle Insurance</label>
                    <!-- <input type="text" name="firstname" id="" placeholder="Phone Number"> -->
                    {{ form.vehicle_insurance }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <button class="w-100">Submit For Verification</button>
            </div>
        </div>
    </form>

</div>

{% endblock content %}

{% block style %}
<!-- <style>
    /* Style the dropdown container */
    .dropdown-container {
        position: relative;
        display: inline-block;
    }

    /* Style the input field */
    input[type="number"] {
        width: 100%;
        padding: 8px;
        box-sizing: border-box;
    }

    /* Style the datalist */
    datalist {
        position: absolute;
        z-index: 1;
        background-color: #fff;
        box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
        list-style-type: none;
        margin: 0;
        padding: 0;
    }

    /* Style the options within the datalist */
    datalist option {
        padding: 8px;
    }
</style> -->
{% endblock style %}